version: 0.2

phases:
  pre_build:
    commands:
      - echo "aws setting..."
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id $aws_access_key_id
      - aws configure set aws_secret_access_key $aws_secret_access_key
      - echo "aws setting complete"
      - CURRENT_TG_ARN=$(aws elbv2 describe-listeners --listener-arns $(aws elbv2 describe-load-balancers --load-balancer-arns $LB_ARN --query 'LoadBalancers[].{ListenerArns:ListenerArns}' --output text) --query 'Listeners[].{DefaultActions:DefaultActions}' --output text | grep 'TargetGroupArn' | awk '{print $2}')
      - CURRENT_TG_NAME=$(aws elbv2 describe-target-groups --target-group-arns $CURRENT_TG_ARN --query 'TargetGroups[].{TargetGroupName:TargetGroupName}' --output text)
      - |
        if [ "$CURRENT_TG_NAME" = "blue" ];then NEXT=green 
        else NEXT=blue 
        fi
      - echo "Installing HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Validating packer.json"
      - ./packer validate packer.json
  build:
    commands:
      # test here if you need
      - ./packer build packer.json
      - ami_id=$(cat manifest.json | jq -r .builds[0].artifact_id |  cut -d':' -f2)
      - echo $ami_id
  post_build:
    commands:
      - echo "HashiCorp Packer build completed on `date`"
      - template_data=$(printf '{"ImageId":"%s","InstanceType":"%s"}' "$ami_id" "t2.micro")
      - template_version=$(aws ec2 create-launch-template-version --launch-template-id $LAUNCH_TEMPLATE --launch-template-data $template_data --query 'LaunchTemplateVersion.VersionNumber')
      - version_info=$(printf '{"Version":"%s","LaunchTemplateId":"%s"}' "$template_version" "$LAUNCH_TEMPLATE")
      - echo $version_info
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name green --launch-template $version_info
artifacts:
  files:
    - '**/*'
